# Generated by Django 4.2.20 on 2025-05-21 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("phantom_auth", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="phantomuser",
            name="token_balance",
            field=models.IntegerField(default=0),
        ),
    ]
