# Generated by Django 4.2.20 on 2025-05-21 12:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("streaming", "0002_track_cover_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="listeningsession",
            old_name="started_at",
            new_name="start_time",
        ),
        migrations.RemoveField(
            model_name="listeningsession",
            name="listened_seconds",
        ),
        migrations.RemoveField(
            model_name="listeningsession",
            name="user",
        ),
        migrations.AddField(
            model_name="listeningsession",
            name="end_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="listeningsession",
            name="public_key",
            field=models.CharField(default=0, max_length=64),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="ListeningSessionModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("listened_seconds", models.IntegerField(default=0)),
                ("rewarded", models.BooleanField(default=False)),
                (
                    "track",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="streaming.track",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
